import test from 'node:test';import assert from 'node:assert/strict';import {createRealityLattice} from '../src/core/reality-engine.js';import {STANDARD,QUANTUM_BRANCHING,CPT_MIRROR,CUSTOM_LAWS,ACTIVE_RESEARCH,getRuleSet} from '../src/core/physics-rules.js';import {createRealityState} from '../src/core/reality-state.js';import {mirrorState,invertMatterState,transformState,rewindState} from '../src/core/transformations.js';
test('boots with observed, quantum, mirror, anti, alternate, research, higher and custom worlds',()=>{const e=createRealityLattice();assert.ok(e.realties.size>=8);for(const id of ['R-OBSERVED','R-QUANTUM','R-MIRROR','R-ANTIMATTER','R-ALTERNATE','R-RESEARCH','R-HYPER','R-CUSTOM'])assert.ok(e.get(id))});
test('physics provenance is metadata',()=>{assert.equal(getRuleSet(STANDARD.id).category,'A');assert.equal(getRuleSet(QUANTUM_BRANCHING.id).category,'B');assert.equal(getRuleSet(ACTIVE_RESEARCH.id).category,'C');assert.equal(getRuleSet(CUSTOM_LAWS.id).category,'E')});
test('fork preserves lineage and direct edge',()=>{const e=createRealityLattice(),b=e.forkReality('R-OBSERVED',{id:'R-B1',name:'History B'});assert.deepEqual(b.parentIds,['R-OBSERVED']);assert.ok(b.lineage.ancestors.includes('R-OBSERVED'));assert.ok([...e.edges.values()].some(x=>x.from==='R-OBSERVED'&&x.to==='R-B1'&&x.type==='fork'))});
test('mirror maps charge, parity-space and time direction',()=>{const s=createRealityLattice().get('R-OBSERVED'),m=mirrorState(s);assert.equal(m.lawSetId,CPT_MIRROR.id);assert.equal(m.time,-s.time);assert.deepEqual(m.entities[1].position.slice(0,3),s.entities[1].position.slice(0,3).map(v=>-v))});
test('antimatter transformation flips matter label',()=>{const s=createRealityLattice().get('R-OBSERVED'),a=invertMatterState(s);assert.equal(a.lawSetId,'antimatter-sector');assert.equal(a.entities[0].matterKind,'antimatter')});
test('custom and research transformations change law set',()=>{const s=createRealityLattice().get('R-OBSERVED');assert.equal(transformState(s,CUSTOM_LAWS.id).lawSetId,CUSTOM_LAWS.id);assert.equal(transformState(s,ACTIVE_RESEARCH.id).lawSetId,ACTIVE_RESEARCH.id)});
test('rewind preserves lineage',()=>{const s=createRealityLattice().get('R-OBSERVED'),a={...s,time:12},n=rewindState(a,5);assert.equal(n.time,7);assert.ok(n.lineage.ancestors.includes('R-OBSERVED'))});
test('merge preserves unique entity lineage',()=>{const e=createRealityLattice(),a=e.forkReality('R-OBSERVED',{id:'R-A'}),b=e.forkReality('R-OBSERVED',{id:'R-B'});b.entities.push({...b.entities[0],id:'observer-b',lineageId:'observer-b'});const m=e.mergeReality(a.id,b.id,{id:'R-MERGED'});assert.equal(m.parentIds.length,2);assert.ok(m.entities.some(x=>x.lineageId==='observer-b'))});
test('time direction is rule-driven',()=>{const e=createRealityLattice(),a=e.get('R-OBSERVED').time,b=e.get('R-MIRROR').time;e.advanceTime('R-OBSERVED',1);e.advanceTime('R-MIRROR',1);assert.equal(e.get('R-OBSERVED').time,a+1);assert.equal(e.get('R-MIRROR').time,b-1)});
test('higher-dimensional state is representable',()=>{const s=createRealityState({id:'R-4D',name:'4D Test',lawSetId:'higher-dimensional',dimension:{spatial:4,temporal:1}});assert.equal(s.dimension.spatial,4)})
test('physics simulation updates state and records causality',()=>{const e=createRealityLattice(),s=e.get('R-OBSERVED');const before=[...s.entities[2].position];s.entities[2].velocity=[.5,0,0,0];e.advanceTime(s.id,1,{gravity:false});assert.notDeepEqual(s.entities[2].position,before);assert.ok(s.causalGraph.length>=1);assert.ok(s.entities[2].momentum[0]>0)});
test('quantum observation forks because its rule set enables branching',()=>{const e=createRealityLattice(),before=e.realties.size,b=e.observeReality('R-QUANTUM',{branch:true,label:'test measurement'});assert.ok(e.realties.size>before);assert.equal(b.parentIds[0],'R-QUANTUM');assert.equal(b.kind,'observation-branch')});
test('entity lineage survives generated mirror and antimatter worlds',()=>{const e=createRealityLattice(),source=e.get('R-OBSERVED'),mirror=e.mirrorReality(source.id),anti=e.invertMatter(source.id);assert.equal(mirror.entities[0].lineageId,source.entities[0].lineageId);assert.equal(anti.entities[0].lineageId,source.entities[0].lineageId)});
