export const MODEL_CATEGORIES=Object.freeze({ESTABLISHED:'A',THEORETICAL:'B',ACTIVE_RESEARCH:'C',SPECULATIVE:'D',SOFTWARE:'E'});
const deepFreeze=v=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const x of Object.values(v))deepFreeze(x);return Object.freeze(v)};
function rules(d){return deepFreeze({schemaVersion:'physics-ruleset-0.26',id:d.id,name:d.name,category:d.category,status:d.status,description:d.description,constants:{G:6.67430e-11,c:299792458,hbar:1.054571817e-34,...d.constants},dimensions:{spatial:3,temporal:1,metricSignature:'-+++',...d.dimensions},interactions:{gravity:'newtonian-approximation',electromagnetism:'maxwell-inspired',custom:[],...d.interactions},conservation:{energy:true,momentum:true,charge:true,information:true,...d.conservation},causality:{maxSignalSpeed:d.constants?.c??299792458,locality:true,...d.causality},timeModel:{kind:'continuous',direction:1,reversible:false,branching:false,...d.timeModel},observation:{causesBranching:false,rule:'record-only',...d.observation}})}
export const STANDARD=rules({id:'standard-observed',name:'Observed / Standard-Inspired',category:'A',status:'grounded',description:'Software model using familiar constants and conservation/causal defaults inspired by established physics.'});
export const QUANTUM_BRANCHING=rules({id:'quantum-branching',name:'Quantum Branching Inspired',category:'B',status:'interpretive-model',description:'Software interpretation layer in which selected observations may create explicit world branches.',timeModel:{branching:true},observation:{causesBranching:true,rule:'branch-on-observation'}});
export const CPT_MIRROR=rules({id:'cpt-mirror',name:'CPT / Mirror Inspired',category:'B',status:'hypothesis-model',description:'Software transform inspired by CPT symmetry and cosmological mirror/anti-universe proposals.',timeModel:{direction:-1,reversible:true}});
export const ANTIMATTER=rules({id:'antimatter-sector',name:'Antimatter Sector',category:'A',status:'matter-antimatter-model',description:'Sector model that swaps matter labels and charge signs.'});
export const ACTIVE_RESEARCH=rules({id:'research-frontier',name:'Research Frontier',category:'C',status:'open-research-model',description:'Placeholder family for unresolved or actively investigated physics such as dark sectors and unknown cosmological mechanisms.'});
export const HIGHER_DIMENSION=rules({id:'higher-dimensional',name:'Higher-Dimensional Projection',category:'D',status:'simulation-model',description:'Projection model with an additional spatial coordinate represented through slicing.',dimensions:{spatial:4,temporal:1,metricSignature:'-++++'}});
export const CUSTOM_LAWS=rules({id:'custom-laws',name:'Custom Physics Sandbox',category:'E',status:'fictional-software',description:'Programmable rule set. Coherency is the primary requirement.',constants:{G:1,c:12,hbar:1},interactions:{gravity:'configurable',electromagnetism:'configurable',custom:['mana-field','domain-boundary']},conservation:{energy:true,momentum:true,charge:false,information:true},causality:{maxSignalSpeed:12,locality:true},timeModel:{kind:'continuous',direction:1,reversible:true,branching:true}});
export const RULESETS=Object.freeze(Object.fromEntries([STANDARD,QUANTUM_BRANCHING,CPT_MIRROR,ANTIMATTER,ACTIVE_RESEARCH,HIGHER_DIMENSION,CUSTOM_LAWS].map(v=>[v.id,v])));
export function getRuleSet(id){const x=RULESETS[id];if(!x)throw new Error('Unknown PhysicsRuleSet: '+id);return x}