import {STANDARD,QUANTUM_BRANCHING,CPT_MIRROR,CUSTOM_LAWS,ANTIMATTER,ACTIVE_RESEARCH,HIGHER_DIMENSION,getRuleSet} from './physics-rules.js';
import {createRealityState,cloneRealityState,recordHistory,recalculateSummaries} from './reality-state.js';
import {invertMatterState,mirrorState,transformState,rewindState} from './transformations.js';
import {stepReality} from './physics-simulation.js';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));const uid=p=>p+'_'+Math.random().toString(36).slice(2,10);
function compatible(a,b){return a.lawSetId===b.lawSetId&&a.dimension.spatial===b.dimension.spatial&&a.dimension.temporal===b.dimension.temporal}
export class RealityLatticeEngine{
constructor(){this.realties=new Map();this.edges=new Map();this.history=[];this.selectedId='R-OBSERVED';this.clock=0;this.#seed()}
#insert(s){this.realties.set(s.id,s);return s}#link(from,to,type,metadata={}){const edge={id:'edge_'+this.edges.size.toString(36),from,to,type,active:true,metadata:clone(metadata)};this.edges.set(edge.id,edge);return edge}
#seed(){
const observed=createRealityState({id:'R-OBSERVED',name:'Observed Reality',kind:'observed',category:STANDARD.category,lawSetId:STANDARD.id,metadata:{status:'grounded-inspiration',canonical:true},entities:[{id:'observer-1',type:'observer',mass:70,energy:70,position:[0,0,0]},{id:'star-1',type:'star',mass:1e30,energy:1e40,position:[2.8,.8,-1.6]},{id:'photon-1',type:'photon',energy:1000,position:[-2.2,1.5,1.4],velocity:[1,0,0]}],entropy:1000,information:8});
const quantum=createRealityState({id:'R-QUANTUM',name:'Quantum Possibility',kind:'quantum-branch',category:QUANTUM_BRANCHING.category,lawSetId:QUANTUM_BRANCHING.id,parentIds:[observed.id],entities:observed.entities,metadata:{status:'interpretive-model'}});
const mirror=mirrorState(observed);mirror.id='R-MIRROR';mirror.name='CPT Mirror';mirror.lineage.originId=observed.id;
const anti=invertMatterState(observed);anti.id='R-ANTIMATTER';anti.name='Antimatter Reality';anti.lineage.originId=observed.id;
const alternate=cloneRealityState(observed,{id:'R-ALTERNATE',name:'Alternate History',kind:'alternate-history',category:'D',parentIds:[observed.id],branchId:'branch:alternate',timelineId:'timeline:alternate',metadata:{status:'software-branch',divergence:'initial-condition change'},entities:observed.entities.map(e=>({...e,position:[(e.position?.[0]||0)*.7,(e.position?.[1]||0)+.9,(e.position?.[2]||0)-.6]))});
const research=transformState(observed,ACTIVE_RESEARCH.id);research.id='R-RESEARCH';research.name='Research Frontier';research.kind='active-research';research.metadata={...research.metadata,status:'open-research-model',subject:'dark-sector / cosmology placeholders'};
const higher=transformState(observed,HIGHER_DIMENSION.id);higher.id='R-HYPER';higher.name='Higher-Dimensional World';higher.kind='higher-dimensional';
const custom=transformState(observed,CUSTOM_LAWS.id);custom.id='R-CUSTOM';custom.name='Custom Law Laboratory';
for(const s of [observed,quantum,mirror,anti,alternate,research,higher,custom])this.#insert(s);
this.#link(observed.id,quantum.id,'fork',{label:'possibility space'});this.#link(observed.id,mirror.id,'mirror',{label:'CPT-inspired mapping'});this.#link(observed.id,anti.id,'anti',{label:'matter inversion'});this.#link(observed.id,alternate.id,'fork',{label:'alternate history'});this.#link(observed.id,research.id,'research',{label:'active research model'});this.#link(observed.id,higher.id,'transform',{label:'higher-dimensional projection'});this.#link(observed.id,custom.id,'transform',{label:'programmable laws'});recordHistory(observed,{type:'engine-seed',time:0})
}
get(id){const s=this.realties.get(id);if(!s)throw new Error('Unknown reality: '+id);return s}list(){return [...this.realties.values()]}select(id){this.get(id);this.selectedId=id;return this.get(id)}
forkReality(sourceId,{id=uid('R-BRANCH'),name='Alternate Branch',kind='alternate-history',patch={}}={}){const source=this.get(sourceId),n=cloneRealityState(source,{id,name,kind,branchId:uid('branch'),timelineId:uid('timeline'),parentIds:[source.id],metadata:{...clone(source.metadata),forkedFrom:source.id,forkPatch:clone(patch)},lineage:{ancestors:[...(source.lineage.ancestors||[]),source.id],transforms:[...(source.lineage.transforms||[]),{type:'fork',patch:clone(patch)}]}});if(Array.isArray(patch.entities))n.entities=patch.entities;if(patch.time!==undefined)n.time=Number(patch.time);if(patch.entropy!==undefined)n.entropy=Math.max(0,Number(patch.entropy));recalculateSummaries(n);source.childIds.push(n.id);this.#insert(n);this.#link(source.id,n.id,'fork',{patch:clone(patch)});this.history.push({type:'fork',from:source.id,to:n.id});return n}
mergeReality(aId,bId,{id=uid('R-MERGED'),name='Merged Reality'}={}){const a=this.get(aId),b=this.get(bId);if(!compatible(a,b))throw new Error('Realities are incompatible for merge: laws/dimensions differ');const map=new Map(a.entities.map(e=>[e.lineageId,clone(e)]));for(const e of b.entities)if(!map.has(e.lineageId))map.set(e.lineageId,clone(e));const n=createRealityState({id,name,kind:'merged',category:a.category,lawSetId:a.lawSetId,parentIds:[a.id,b.id],timelineId:uid('timeline'),dimension:clone(a.dimension),time:Math.min(a.time,b.time),entropy:(a.entropy+b.entropy)/2,information:Math.max(a.information,b.information),entities:[...map.values()],metadata:{mergedFrom:[a.id,b.id]}});n.lineage={originId:a.lineage.originId||a.id,ancestors:[...new Set([...(a.lineage.ancestors||[]),...(b.lineage.ancestors||[]),a.id,b.id])],transforms:[{type:'merge',sources:[a.id,b.id]}]};this.#insert(n);this.#link(a.id,n.id,'merge',{partner:b.id});this.#link(b.id,n.id,'merge',{partner:a.id});this.history.push({type:'merge',from:[a.id,b.id],to:n.id});return n}
mirrorReality(sourceId){const source=this.get(sourceId),n=mirrorState(source);if(this.realties.has(n.id))n.id=uid('R-MIRROR');n.name=source.name+' · CPT Mirror';source.childIds.push(n.id);this.#insert(n);this.#link(source.id,n.id,'mirror',{transform:'CPT-inspired'});this.history.push({type:'mirror',from:source.id,to:n.id});return n}
invertMatter(sourceId){const source=this.get(sourceId),n=invertMatterState(source);if(this.realties.has(n.id))n.id=uid('R-ANTI');n.name=source.name+' · Antimatter';source.childIds.push(n.id);this.#insert(n);this.#link(source.id,n.id,'anti',{transform:'matter-inversion'});this.history.push({type:'anti',from:source.id,to:n.id});return n}
transformReality(sourceId,targetRuleSetId){const source=this.get(sourceId),n=transformState(source,targetRuleSetId);if(this.realties.has(n.id))n.id=uid('R-TRANSFORM');source.childIds.push(n.id);this.#insert(n);this.#link(source.id,n.id,'transform',{targetRuleSetId});this.history.push({type:'transform',from:source.id,to:n.id,targetRuleSetId});return n}
observeReality(sourceId,{branch=true,label='observation'}={}){const source=this.get(sourceId);recordHistory(source,{type:'observation',label,time:source.time});if(branch&&getRuleSet(source.lawSetId).observation.causesBranching)return this.forkReality(sourceId,{name:source.name+' · observed branch',kind:'observation-branch',patch:{metadata:{observation:label}}});return source}
advanceTime(sourceId,dt=.1,options={}){const s=this.get(sourceId);return stepReality(s,dt,options)}
advanceAll(dt=.05){for(const s of this.realties.values())this.advanceTime(s.id,dt);return this.snapshot()}
rewindSimulation(id,dt=1){const source=this.get(id),n=rewindState(source,dt);this.#insert(n);this.#link(source.id,n.id,'rewind',{dt});this.history.push({type:'rewind',from:source.id,to:n.id,dt});return n}
traceLineage(entityId){return this.list().filter(r=>r.entities.some(e=>e.lineageId===entityId||e.id===entityId)).map(r=>({realityId:r.id,name:r.name,entityIds:r.entities.filter(e=>e.lineageId===entityId||e.id===entityId).map(e=>e.id),ancestors:r.lineage.ancestors}))}
compareReality(aId,bId){const a=this.get(aId),b=this.get(bId),ids=new Set([...a.entities.map(e=>e.lineageId),...b.entities.map(e=>e.lineageId)]);return{a:{id:a.id,lawSetId:a.lawSetId,time:a.time,entropy:a.entropy},b:{id:b.id,lawSetId:b.lawSetId,time:b.time,entropy:b.entropy},compatible:compatible(a,b),entityDelta:[...ids].map(id=>({lineageId:id,presentInA:a.entities.some(e=>e.lineageId===id),presentInB:b.entities.some(e=>e.lineageId===id)}))}}
snapshot(){return{schemaVersion:'reality-lattice-0.26',realities:this.list().map(clone),edges:[...this.edges.values()].map(clone),history:clone(this.history),selectedId:this.selectedId}}
}
export function createRealityLattice(){return new RealityLatticeEngine()}